# Build Windows workflow
name: deploy

on:
  push:
    tags: 
      - v*
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Windows
        run: pyinstaller --clean --noconfirm specs/windows-terminservice.spec --add-data "tools/cloudscraper;./cloudscraper/"
      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: vaccipy-windows.zip
      - name: Store windows build artifact
        uses: actions/upload-artifact@v2
        with:
          name: vaccipy-windows
          path: vaccipy-windows.zip
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Linux
        run: pyinstaller --clean --noconfirm specs/linux-64-terminservice.spec --add-data "tools/cloudscraper:./cloudscraper/"
      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: vaccipy-ubuntu.zip
      - name: Store windows build artifact
        uses: actions/upload-artifact@v2
        with:
          name: vaccipy-ubuntu
          path: vaccipy-ubuntu.zip
  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    steps:
      - name: Download build files
        uses: actions/download-artifact@v2
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            vaccipy-windows/vaccipy-windows.zip
            vaccipy-ubuntu/vaccipy-ubuntu.zip
